ใน ep ก่อน ๆ เราได้เรียนรู้การจัดการมิติ การเลือกข้อมูลด้วย [indexing, slicing](https://www.bualabs.com/archives/1749/how-to-pytorch-reshape-squeeze-unsqueeze-flatten-manipulate-shape-high-order-dimensions-tensor-ep-2/) กันไปแล้ว ใน ep นี้ เราจะมาเรียนรู้การเลือกข้อมูล Tensor ที่ซับซ้อนยิ่งขึ้น ด้วย gather อ่านเอกสารแล้วอาจจะยังงง เรามาดูตัวอย่างกันเลยดีกว่า

In [0]:
import torch
from torch import tensor

# 1. ข้อมูลตัวอย่าง

สร้าง tensor 2 มิติ ขนาด 4 x 10 โดยรันเลข แถว และ หลัก จะได้ดูง่าย

In [18]:
x = torch.arange(40).reshape(4, 10)
x.shape

torch.Size([4, 10])

In [19]:
x

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

เราสามารถ เลือกด้วย [indexing](https://www.bualabs.com/archives/1629/what-is-tensor-element-wise-broadcasting-operations-high-order-tensor-numpy-array-matrix-vector-tensor-ep-1/) ตามปกติ

In [8]:
x[1, :]

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
x[:, 2]

tensor([ 2, 12, 22, 32])

# 2. gather

ถ้าเราต้องการ เลือกข้อมูล แบบอิสระตามใจ เช่น ตัว 3 แถวแรก, ตัว 5 แถวสอง, ตัว 7 แถวสาม, ตัว 9 แถวสี่ จะทำอย่างไร คำตอบ คือ ใช้ gather

In [25]:
idx = torch.LongTensor([3, 5, 7, 9]).unsqueeze(-1)
idx.shape

torch.Size([4, 1])

เบื้องต้น เราต้องทำให้ index ที่ใช้ในการเลือก มีมิติเหมือนข้อมูลที่มิติ ยกเว้นมิติที่ใช้เลือก ให้เท่ากับ 1 ดังด้านบน ข้อมูลเป็น 4x10, index เป็น 4x1

In [26]:
idx

tensor([[3],
        [5],
        [7],
        [9]])

เรียก gather ข้อมูลใน x ในมิติที่ 1 ด้วย index ที่กำหนด

In [27]:
dim = 1
x.gather(dim, idx)

tensor([[ 3],
        [15],
        [27],
        [39]])

output ที่ได้ออกมาจะมีมิติ เหมือน index เสมอ

# 3. gather ทีละหลาย ๆ ตัว

เราไม่จำเป็นต้องเลือกมิติละตัว เราสามารถใส่มิติที่เลือกมากกว่า 1 ได้ เช่น ตัวอย่างด้านล่าง เราจะเปลี่ยนจากเลือก 1 ตัว เป็นเลือกทีละ 2 ตัว 4x1 เป็น 4x2 โดย เลือก

* ตัว 3, 4 แถวแรก
* ตัว 5, 6 แถวสอง
* ตัว 7, 8 แถวสาม
* ตัว 9, 0 แถวสี่

In [37]:
idx = torch.LongTensor([[3, 4], [5, 6], [7, 8], [9, 0]])
idx.shape

torch.Size([4, 2])

เราจะทำให้ index ที่ใช้ในการเลือก มีมิติเหมือนข้อมูลที่มิติ ยกเว้นมิติที่ใช้เลือก ให้เท่ากับ 2 ดังด้านบน ข้อมูลเป็น 4x10, index เป็น 4x2

In [38]:
idx

tensor([[3, 4],
        [5, 6],
        [7, 8],
        [9, 0]])

เรียก gather ข้อมูลใน x ในมิติที่ 1 ด้วย index ที่กำหนด

In [39]:
dim = 1
x.gather(dim, idx)

tensor([[ 3,  4],
        [15, 16],
        [27, 28],
        [39, 30]])

เราสามารถเลือกทีทีละหลายตัวไม่จำกัด สามารถเพิ่มขนาดของ index ไปเรื่อย ๆ output ที่ได้ออกมาจะมีมิติ เหมือน index เสมอ

# 4. gather ข้อมูล 3 มิติ

สร้างข้อมูลตัวอย่าง 3 มิติ ให้มีเลขหลักหน่วย สิบ ร้อย ตามมิติ จะได้ดูง่าย

In [78]:
a = torch.arange(0, 8, step=1).unsqueeze(0).unsqueeze(0)
b = torch.arange(0, 60, step=10).unsqueeze(-1).unsqueeze(0)
c = torch.arange(0, 400, step=100).unsqueeze(-1).unsqueeze(-1)

x = a + b + c
x.shape

torch.Size([4, 6, 8])

ได้มิติเป็น 4x6x8

In [79]:
x

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7],
         [ 10,  11,  12,  13,  14,  15,  16,  17],
         [ 20,  21,  22,  23,  24,  25,  26,  27],
         [ 30,  31,  32,  33,  34,  35,  36,  37],
         [ 40,  41,  42,  43,  44,  45,  46,  47],
         [ 50,  51,  52,  53,  54,  55,  56,  57]],

        [[100, 101, 102, 103, 104, 105, 106, 107],
         [110, 111, 112, 113, 114, 115, 116, 117],
         [120, 121, 122, 123, 124, 125, 126, 127],
         [130, 131, 132, 133, 134, 135, 136, 137],
         [140, 141, 142, 143, 144, 145, 146, 147],
         [150, 151, 152, 153, 154, 155, 156, 157]],

        [[200, 201, 202, 203, 204, 205, 206, 207],
         [210, 211, 212, 213, 214, 215, 216, 217],
         [220, 221, 222, 223, 224, 225, 226, 227],
         [230, 231, 232, 233, 234, 235, 236, 237],
         [240, 241, 242, 243, 244, 245, 246, 247],
         [250, 251, 252, 253, 254, 255, 256, 257]],

        [[300, 301, 302, 303, 304, 305, 306, 307],
         [310, 311, 312, 

เราสามารถ เลือกด้วย [indexing](https://www.bualabs.com/archives/1629/what-is-tensor-element-wise-broadcasting-operations-high-order-tensor-numpy-array-matrix-vector-tensor-ep-1/) ตามปกติ

In [80]:
x[1, 2, 3], x[2, 1, 0], x[2, 5, 6]

(tensor(123), tensor(210), tensor(256))

In [81]:
x[:, 3, 2]

tensor([ 32, 132, 232, 332])

In [82]:
x[:, 2, :]

tensor([[ 20,  21,  22,  23,  24,  25,  26,  27],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [220, 221, 222, 223, 224, 225, 226, 227],
        [320, 321, 322, 323, 324, 325, 326, 327]])

ในเคสตัวอย่างเช่น Sequence Model ข้อมูลตัวอย่าง มี 3 มิติ เช่น BATCH_SIZE x MAX_SEQ_LEN x HIDDEN_STATE สมมติเราต้องการเลือก Hidden State ทั้งหมดของ Batch ที่ตัวสุดท้ายของ Sequence เรามีลิสต์ความยาวของ Sequence ใน Batch ดังด้านล่าง

In [102]:
lens = torch.LongTensor([4, 5, 4, 3]).unsqueeze(-1).unsqueeze(-1)
lens.shape

torch.Size([4, 1, 1])

เราต้องสร้าง index จาก lens ให้มิติเป็น BATCH_SIZE x 1 x HIDDEN_STATE หรือ 4 x 1 x 8

เนื่องจาก lens เท่ากับ [batch size](https://www.bualabs.com/archives/729/what-is-batch-size-in-deep-neural-networks-how-to-adjust-machine-learning-model-accuracy-deep-learning-hyperparameter-tuning-ep-2/) อยู่แล้ว เราสามารถใช้ repeat ได้เลย

In [103]:
idx = lens.repeat(1, 1, 8)
idx.shape

torch.Size([4, 1, 8])

In [105]:
idx

tensor([[[4, 4, 4, 4, 4, 4, 4, 4]],

        [[5, 5, 5, 5, 5, 5, 5, 5]],

        [[4, 4, 4, 4, 4, 4, 4, 4]],

        [[3, 3, 3, 3, 3, 3, 3, 3]]])

In [106]:
dim = 1
x.gather(dim, idx)

tensor([[[ 40,  41,  42,  43,  44,  45,  46,  47]],

        [[150, 151, 152, 153, 154, 155, 156, 157]],

        [[240, 241, 242, 243, 244, 245, 246, 247]],

        [[330, 331, 332, 333, 334, 335, 336, 337]]])

เราจะได้ 4 5 4 3 ของมิติที่สอง ออกมาในทุก มิติหนึ่ง และ มิติสาม สังเกต หลักร้อยจะไล่ 0-3 และหลักหน่วยจะไล่ 0-8 ในขณะที่หลักสิบ เป็น 4 5 4 3 ตามที่เรากำหนดใน index

# 5. สรุป

* เราสามารถใช้ torch.Tensor.gather ในการเลือก Tensor ที่ยืดหยุ่นมากกว่า indexing ปกติ
* เวลาใช้งานควรศึกษามิติของข้อมูลตัวอย่าง และออกแบบ dim และ index ให้เหมาะสม
* ในการสร้าง index สามารถใช้ [unsqueeze](https://www.bualabs.com/archives/1749/how-to-pytorch-reshape-squeeze-unsqueeze-flatten-manipulate-shape-high-order-dimensions-tensor-ep-2/), repeat ช่วยได้
* เราสามารถ apply วิธีเดียวกันนี้ กับ Tensor 4 มิติ 5 มิติ ขึ้นไปได้ไม่จำกัด

# Credit

* https://medium.com/analytics-vidhya/understanding-indexing-with-pytorch-gather-33717a84ebc4
* https://pytorch.org/docs/stable/tensors.html
* https://stackoverflow.com/questions/50999977/what-does-the-gather-function-do-in-pytorch-in-layman-terms
* https://www.tensorflow.org/api_docs/python/tf/gather